#Spring Boot Config

#端口
server:
  port: 8082
  servlet:
    context-path: /tmall

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tmalldemodb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      connection-timeout: 5000
      max-lifetime: 60000
  mail:
    host: smtp.163.com
    username: fanshuye1304@163.com
    password: fanshuye1304
  freemarker:
    suffix: .html
    request-context-attribute: request
    charset: UTF-8
  aop:
    proxy-target-class: true
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20MB

#MyBatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xq.tmall.entity;
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    meta-object-handler: com.xq.tmall.config.mybatis.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: false # 开启驼峰命名转换法
    cache-enabled: true
    #Mybatis返回null值不显示
    call-setters-on-nulls: true
#logging
logging:
  level:
    com.xq.tmall: DEBUG
  #file: ./logs/xqdjzwwexin-log.log

#短信平台配置
sms:
  open: true
  sms-type: huyi
  sign-name: aa
  api-id: C68828166
  api-key: e7814b5b690142a8b36bc17bfc4ec8a4
  url: http://106.ihuyi.cn/webservice/sms.php?method=Submit
